name: Build

on:
  pull_request

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Print Go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .
